### ISSUE TITLE
Fix endless setTimeout upstream in generic-pool

### ISSUE THREAD

**Issue by yhahn** [mapbox/tilelive-bridge#29]
https://github.com/mapbox/tilelive-bridge/commit/bc33b569289e84c22d3fd74f79259caaa0d26f67#diff-c1129c8b045390789fa8ff62f2c6b4a9R308

**Comment by springmeyer** [comment]
hrmmmmmmmmm, this is still replicable with `generic-pool@2.2.1`

**Comment by springmeyer** [comment]
found it: we were not closing the sources pool correctly in the tests.
