### ISSUE TITLE
Update map XML even if it hasn't changed

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/tilelive-bridge#35]
In Mapbox Studio I want to refresh a list of fonts that a map references every time I refresh the map, even if I didn't change the style. Update is skipped if the style hasn't changed:  
https://github.com/mapbox/tilelive-bridge/blob/617910431a0edb089dda9a47720ffa5ab656d22e/index.js#L71-L72

**Comment by springmeyer** [comment]
This appears fixed by #81
