### ISSUE TITLE
Reduce memory usage in getVector

### ISSUE THREAD

**Issue by springmeyer** [mapbox/tilelive-bridge#45]
There are some obvious optimizations we can make to getVector to reduce the amount of memory allocated in the JS/V8 heap which should help performance in large rendering jobs by avoiding GC churn. And it is becoming clear that memory usage is overall higher on Windows so finding ways to keep memory down will help windows performance in particular.

Here is a shortlist of optimization ideas:

1) Fix `vtile.isSolid` key to work

Not sure what was wrong with the key returned from `vtile.isSolid`, but the hack to workaround is expensive for large vtile buffers. We should replace https://github.com/mapbox/tilelive-bridge/blob/d56e0bed2d421e3a4d52bb479fde35d63e08a3f7/index.js#L187-L193 with something that does not require a crypto call on the entire buffer.

2) Avoid passing uncompressed buffer from C++ to JS

Instead of calling `vtile.getData()` and passing that to `zlib.gzip` we could save memory and perform faster if we implemented `vtile.gzip` so that the uncompressed vtile buffer never passes into JS land: https://github.com/mapbox/tilelive-bridge/blob/d56e0bed2d421e3a4d52bb479fde35d63e08a3f7/index.js#L172-L173. And we should make `vtile.gzip` async for best speed.

3) Call vtile.clear()

Before returning [here](https://github.com/mapbox/tilelive-bridge/blob/d56e0bed2d421e3a4d52bb479fde35d63e08a3f7/index.js#L195) we could benchmark calling `vtile.clear()`. This would drop all the internal memory allocated for the vtile object tree immediately instead of waiting for GC to clean up the object. This might help reduce crashes from OOM on windows which are common because the V8 GC does not currently get any hints from node-mapnik about vtile-allocated memory (like it does for mapnik.Images)

/cc @BergWerkGIS

**Comment by yhahn** [comment]
:+1: let me know if you need anything here.

It would be very convenient to have `vtile.getData()` take an option to get things back gzipped and `vtile.setData()` to consume the buffer intelligently (gunzipping if necessary).

**Comment by springmeyer** [comment]
@yhahn any reason to support pure zlib from your perspective or only gzip? One specific reason I ask is that I've got gzip auto-detection working but there is a bug I'm still trying to flush out around zlib detection (https://github.com/mapbox/mapnik-vector-tile/blob/master/test/vector_tile.cpp#L42 | https://github.com/mapbox/mapnik-vector-tile/blob/master/src/vector_tile_compression.hpp)

**Comment by springmeyer** [comment]
Closing. All of the above ideas are now implemented and landed in https://github.com/mapbox/tilelive-bridge/commit/d89ffd578353519870a0e064f9a9543fe85a336f and the `v1.6.0` release.
