### ISSUE TITLE
Failing tests on Windows with node 0.12.7

### ISSUE THREAD

**Issue by BergWerkGIS** [mapbox/tilelive-bridge#52]
:x:  Two tests are failing with node **0.12.7**:

https://ci.appveyor.com/project/Mapbox/tilelive-bridge/build/1.0.180/job/g97r04oc38n8nk1k#L678

Seems to be some kind of rounding issue:
`17.70388800000005` vs. `17.703888000000063` and
`17.364164500000093` vs. `17.3641645000001`

![image](https://cloud.githubusercontent.com/assets/4549888/9057825/fee4304c-3a9c-11e5-860a-6276ece504ae.png)

-----

:white_check_mark:  Same tests work ok with node **0.10.40**:

https://ci.appveyor.com/project/Mapbox/tilelive-bridge/build/1.0.180/job/g9uw1t34j57iubd3#L662

![image](https://cloud.githubusercontent.com/assets/4549888/9057875/40860732-3a9d-11e5-95f3-e724db58701d.png)

**Comment by flippmoke** [comment]
Fixed by https://github.com/mapbox/tilelive-bridge/commit/c5c8edbf640b5a05c5fa6fd999faede8e04b6efc
