### ISSUE TITLE
Remove deprecated bufferSize and move to render-time buffer_size only

### ISSUE THREAD

**Issue by yhahn** [mapbox/tilelive-bridge#57]
Per @springmeyer's comment here https://github.com/mapbox/tilelive-bridge/pull/56#discussion_r37646505. This is working currently but the goal is to remove the global map bufferSize in the future in mapnik upstream.

Once this happens we'll move to handling buffer_size at the render call only.

cc @springmeyer @flippmoke

**Comment by springmeyer** [comment]
Nothing to do here, was a false alarm: https://github.com/mapbox/tilelive-bridge/pull/56#r37653251
