### ISSUE TITLE
Support for simplifying lines?

### ISSUE THREAD

**Issue by parinporecha** [mapbox/tilelive-bridge#62]
Hi, does tilelive-bridge have a `simplify` feature like MVT does?

I went through the closed issues and https://github.com/mapbox/tilelive-bridge/issues/13 seems like a bummer. Has support been added now or do you have plans for it?

**Comment by springmeyer** [comment]
Yes, see `simplify_distance` which applies to both lines and polygons: https://github.com/mapbox/tilelive-bridge/blob/master/index.js#L165-L186
