### ISSUE TITLE
Coverage of carmen related error cases (getIndexableDocs)

### ISSUE THREAD

**Issue by springmeyer** [mapbox/tilelive-bridge#73]
@sbma44 - one more coverage request. I changed a bunch of `if (err) return callback(err)` to put the `callback...` on another line and this highlighted more lacking coverage of error cases:

https://coveralls.io/builds/4074392/source?filename=index.js#L330

Can you take a look and see if any of these feel worth covering?

**Comment by sbma44** [comment]
I might have to defer to you on the "worth covering" question. Our medium-term goal is to remove this as a dependency from the geocoding pipeline entirely, so my hope is that this code can be retired before too long. Insofar as these sanity checks only cover a small portion of what can go wrong with a carmen tilesource, the payoff here may be questionable. OTOH it won't take me too long if you feel that getting coverage % up is a desirable goal as a general matter.

**Comment by springmeyer** [comment]
thanks, lets call it good enough for now.
