### ISSUE TITLE
Some groups of polygons not retrieved using getTiles with pbf format

### ISSUE THREAD

**Issue by steve9164** [mapbox/tilelive-bridge#77]
Calling `getTile` on [this shapefile](https://dl.dropboxusercontent.com/u/18091071/FID_SA4_2011_AUST.zip) (EPSG:3857 projection, mapnik xml included) only returns some of the geometry. It only returns features from the states NSW and Victoria, but the shapefile has polygons for region boundaries for all of Australia. 

The shapefile has a property called `STE` with a number from 1 to 9 depending on what state each feature is within. NSW and Victoria have `STE` codes 1 & 2. Maybe mapnik is reading the `STE` field as a special field?

Below is a visualisation of the features that are returned by `tilelive-bridge`, and the full set of features defined in the shapefile (as raster tiles from a WMS server using the same shapefile).

#### tilelive-bridge
![sa4 nsw vic](https://cloud.githubusercontent.com/assets/13863530/12840461/bd5e67dc-cc37-11e5-9c18-02252289f5d3.png)

#### Other WMS server
![sa4 all states](https://cloud.githubusercontent.com/assets/13863530/12840462/be380db6-cc37-11e5-8ec0-9d473422813d.png)

Here is the shortest test I could come up with to show the problem. It is very similar to my normal use of the module:

```javascript
// Run `npm install tilelive tilelive-bridge when` to install needed modules
// npm version: 3.3.12
// node version: v5.1.0

'use strict';

let when = require('when');
let nodefn = require('when/node');
let tilelive = require('tilelive');
require('tilelive-bridge').registerProtocols(tilelive);


// Load the mapnik xml file, then for each of the 2 tiles defined try to retrieve the tile from the source
nodefn.call(tilelive.load, 'bridge://C:/FID_SA4_2011_AUST/data.xml').then(function(source) {
    let tiles = [[6,55,36], [6, 58, 38]];
    for (let i = 0; i < tiles.length; i++) {
        // For each tile, call getTile, passing the tile coordinates
        // nodefn.apply calls getTile with the tile coordinates and runs either the first or second 
        // function given in the .then depending on if an error is returned
        nodefn.apply(source.getTile.bind(source), tiles[i]).then(function(tile) {
            console.log('Tile '+ tiles[i].join('/') + ' retrieved successfully');
        }, function(err) {
            console.log('Tile '+ tiles[i].join('/') + ' failed: ' + err);
        });
    }
});
```
The output I get is:

> Tile 6/55/36 failed: Error: Tile does not exist
> Tile 6/58/38 retrieved successfully

The expected outcome is that both tiles are successfully retrieved with geometries.

Here is an excerpt from `ogrinfo` for each of the tiles. I got the spatial extents using `sphericalmercator` module `merc.bbox(55,36,6, false, "900913")`:

##### Tile 6/55/36:

> ogrinfo FID_SA4_2011_AUST.shp -al -so -spat 14401959.121379768 -3130860.678560819 15028131.257091932 -2504688.542848655
> 
> Layer name: FID_SA4_2011_AUST
> Geometry: Polygon
> Feature Count: 20
> ...

##### Tile 6/58/38

> ogrinfo FID_SA4_2011_AUST.shp -al -so -spat 16280475.528516259 -4383204.9499851465 16906647.664228424 -3757032.814272983
> 
> Layer name: FID_SA4_2011_AUST
> Geometry: Polygon
> Feature Count: 46
> ...

So both tiles should have geometry.

**Comment by steve9164** [comment]
It seems the problem my be in mapnik itself. Here is a preview of the same shapefile used in the above tests in:

##### Mapbox Studio:
![sa4 mapbox studio](https://cloud.githubusercontent.com/assets/13863530/12876272/d83cd21a-ce52-11e5-8e52-21458dbeea8a.png)

##### QGIS Browser:
![sa4 qgis browser](https://cloud.githubusercontent.com/assets/13863530/12876273/dbcda224-ce52-11e5-98eb-f9dcba1332f6.png)

Mapbox Studio has exactly the same problem as tilelive-bridge.

**Comment by steve9164** [comment]
After more testing, it seems the issue is in `shapeindex`. The shapefile works without having an index, but then is extremely slow.

**Comment by artemp** [comment]
@steve9164 - I changed `shapeindex` in https://github.com/mapnik/mapnik/commit/2b725dd25746ae8418de18a381ca5792223a8a30 to always skip `null` shapes, somehow this got lost during merges. Let me know it it works for you and I'll close this issue. Thanks for reporting!

**Comment by steve9164** [comment]
Thanks @artemp. Are there build instructions for Mapnik source builds on Windows? I could only find an installation guide for downloading binaries. I ended up buidling Mapnik from source on Ubuntu, using `shapeindex` on all my shapefiles from there and then transferring them back. All of the shapefiles I've tested so far have worked.

**Comment by BergWerkGIS** [comment]
@steve9164  https://github.com/mapbox/windows-builds

Should boil down to these steps:

```
git clone https://github.com/mapbox/windows-builds.git
cd windows-builds
settings.bat
scripts\build.bat
```

Be aware, this might take some time and quite some CPU and RAM.

**Comment by artemp** [comment]
@steve9164 - thanks for testing, closing.
