### ISSUE TITLE
Buffer size for vector tiles is hard-coded

### ISSUE THREAD

**Issue by YenTheFirst** [mapbox/tilelive-bridge#87]
may be related to #57.

Vector tiles are currently generated with a hard-coded buffer size of 256.

mapbox-gl-js has known issues with handling tiles that include geometry well past the extent
(such as https://github.com/mapbox/mapbox-gl-js/issues/2854, https://github.com/mapbox/mapbox-gl-js/issues/2676)

The suggested workaround is to use a smaller buffer size. However, this currently cannot be done without forking tilelive-bridge.

**Comment by springmeyer** [comment]
A smaller buffer size can be set by setting it at the layer level in the Mapnik XML like

```xml
<Layer name="name" buffer-size="5">
```

See also #94
